Revert "Do something weird here just to demonstrate github"
zephyriot/zephyr pull request #2
Opened 2016-12-08 21:38 UTC by MaureenHelm

Reverts zephyriot/zephyr#1

2016-12-08 21:41 UTC, galak requested changes

2016-12-08 21:41 UTC, galak commented on kernel/microkernel/k_semaphore.c
> +					struct k_args *waitTaskArgs = X->Ctxt.args;
here

2016-12-08 21:43 UTC, galak commented on kernel/microkernel/k_semaphore.c
> +					struct k_args *waitTaskArgs = X->Ctxt.args;
another comment

2016-12-08 21:43 UTC, galak approved these changes
Approved!

2016-12-08 21:43 UTC, lpereira requested changes
The divide by zero is fundamental, keep it.

2016-12-08 21:45 UTC, galak commented on kernel/microkernel/k_semaphore.c
> +					struct k_args *waitTaskArgs = X->Ctxt.args;
once more

2016-12-08 21:45 UTC, galak requested changes
change

2016-12-08 22:06 UTC, nashif commented
# Header
# Header 2

2016-12-10 20:22 UTC, nashif commented
abandon

2016-12-10 20:22 UTC, closed without merging